# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 400)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 411))
        self.widget.setMinimumSize(QtCore.QSize(661, 411))
        self.widget.setMaximumSize(QtCore.QSize(661, 411))
        self.widget.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 190, 80, 80))
        self.label_4.setMinimumSize(QtCore.QSize(80, 80))
        self.label_4.setMaximumSize(QtCore.QSize(80, 80))
        self.label_4.setStyleSheet("background-color: rgb(255,255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(110, 300, 101, 21))
        self.label_6.setMinimumSize(QtCore.QSize(101, 21))
        self.label_6.setMaximumSize(QtCore.QSize(101, 21))
        self.label_6.setStyleSheet("font: 18pt \"宋体\";")
        self.label_6.setObjectName("label_6")
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.username_lineEdit.setGeometry(QtCore.QRect(420, 200, 150, 31))
        self.username_lineEdit.setMinimumSize(QtCore.QSize(150, 31))
        self.username_lineEdit.setMaximumSize(QtCore.QSize(150, 31))
        self.username_lineEdit.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.username_lineEdit.setText("")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.register_pushButton = QtWidgets.QPushButton(self.widget)
        self.register_pushButton.setGeometry(QtCore.QRect(360, 310, 81, 41))
        self.register_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 18pt \"宋体\";\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.register_pushButton.setObjectName("register_pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(340, 260, 60, 24))
        self.label_3.setMinimumSize(QtCore.QSize(60, 24))
        self.label_3.setMaximumSize(QtCore.QSize(60, 24))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 18pt \"宋体\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(340, 200, 60, 24))
        self.label_2.setMinimumSize(QtCore.QSize(60, 24))
        self.label_2.setMaximumSize(QtCore.QSize(60, 24))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 18pt \"宋体\";")
        self.label_2.setObjectName("label_2")
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.password_lineEdit.setGeometry(QtCore.QRect(420, 260, 150, 31))
        self.password_lineEdit.setMinimumSize(QtCore.QSize(150, 31))
        self.password_lineEdit.setMaximumSize(QtCore.QSize(150, 31))
        self.password_lineEdit.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.login_pushButton = QtWidgets.QPushButton(self.widget)
        self.login_pushButton.setGeometry(QtCore.QRect(480, 310, 81, 41))
        self.login_pushButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"font: 18pt \"宋体\";\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.login_pushButton.setObjectName("login_pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 661, 141))
        self.label.setMinimumSize(QtCore.QSize(661, 141))
        self.label.setMaximumSize(QtCore.QSize(661, 141))
        self.label.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(120, 30, 421, 61))
        self.label_7.setMinimumSize(QtCore.QSize(421, 61))
        self.label_7.setMaximumSize(QtCore.QSize(421, 61))
        self.label_7.setStyleSheet("font: 20pt \"幼圆\";\n"
"background-color: rgb(85, 170, 255);\n"
"")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "用户登录"))
        self.register_pushButton.setText(_translate("Form", "注册"))
        self.label_3.setText(_translate("Form", "密码:"))
        self.label_2.setText(_translate("Form", "用户:"))
        self.login_pushButton.setText(_translate("Form", "登录"))
        self.label_7.setText(_translate("Form", "架空输电设备其缺陷智能识别系统"))
